### ISSUE TITLE
Environment not available

### ISSUE THREAD

**Issue by pierrebaque** [batra-mlp-lab/divmbest#2]
Hello,

Thank you for providing this code.
I was trying to run the divMbest for segmentation and it turns out that the link that is used to set up the experimental environment,
https://filebox.ece.vt.edu/~senthil/divseg_o2p_env.tar.gz

is not available anymore.

Do you, by any chance, know where I could find these files please?

Thank you.

Regards,

Pierre

**Comment by senthilps8** [comment]
Sorry about that. Fixed it now.
